# Travis: Macos

language: cpp
sudo: required

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      env: ARCH="x86_64"
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6 TEST_CXX14=true BOOST_VERSION=1.61.0

    - os: osx
      env: ARCH="x86_64"
      osx_image: xcode8.2


before_install:
    - if [ `uname` = "Linux" ]; then \
        echo linux 1 \
        echo linux 2 \
      elif [ `uname` = "Darwin" ]; then \
        echo macos 1 \
        echo macos 2 \
      fi

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then hg clone https://bitbucket.org/eigen/eigen#3.3 /tmp/eigen && mkdir /tmp/eigen-build && cd /tmp/eigen-build && cmake . /tmp/eigen && make && sudo make install && cd -; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then hg clone https://bitbucket.org/eigen/eigen#3.3 /tmp/eigen && mkdir /tmp/eigen-build && cd /tmp/eigen-build && cmake . /tmp/eigen && make && sudo make install && cd -; fi

  
notifications:
  email: false
