# Travis: Macos

language: cpp
sudo: required

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      env: ARCH="x86_64"
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6 TEST_CXX14=true BOOST_VERSION=1.61.0

    - os: osx
      env: ARCH="x86_64"
      osx_image: xcode8.2


before_install:
    - if [ `uname` = "Linux" ]; then
          sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
          sudo apt-get update -qq
          sudo apt-get install gettext
          sudo apt-get install pkg-config
          sudo apt-get install cmake
          sudo apt-get install libffi-dev
          sudo apt-get install libicu-dev
          sudo apt-get install libxml2-dev
          sudo apt-get -y install qt55base
          sudo apt-get -y install qt55tools
      elif [ `uname` = "Darwin" ]; then
          brew update
          brew install libffi
          brew install pkg-config libffi 
          brew link --force libffi
          brew install pkgconfig
          brew install icu4c
          brew link icu4c —-force
          brew install gettext
          brew link gettext -—force
          brew install boost
          brew install libxml2
          brew install cmake
          brew install qt5;
      fi

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then hg clone https://bitbucket.org/eigen/eigen#3.3 /tmp/eigen && mkdir /tmp/eigen-build && cd /tmp/eigen-build && cmake . /tmp/eigen && make && sudo make install && cd -; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then hg clone https://bitbucket.org/eigen/eigen#3.3 /tmp/eigen && mkdir /tmp/eigen-build && cd /tmp/eigen-build && cmake . /tmp/eigen && make && sudo make install && cd -; fi

  
notifications:
  email: false
