version: 0.1.6.{build}
image: Visual Studio 2015

environment:
  VS_VERSION: vs2015
  QTDIR64: C:\Qt\5.9\msvc2015_64
  QTDIR: C:\Qt\5.9\msvc2015_64
  BUILD_CHAIN_DIR: c:\build_chain\nelson

branches:
  only:
    - master

platform:
- x64

before_build:
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-x64.git c:\build_chain\nelson-thirdparty-x64
- cd "c:\build_chain\nelson-thirdparty-x64"
- set
- install.bat

after_build:
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -f c:\build_chain/nelson/tools/buildhelp/buildhelp.nls
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -f c:\build_chain/nelson/tools/tests_minimal/runtests_minimal.nls
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -e run('c:\build_chain/nelson/tools/innosetup/innosetup.nls');exit
- iscc c:\build_chain/nelson/tools/innosetup/Nelson.iss
- echo ici 1
- copy /Y c:\build_chain\nelson\Nelson-*.exe c:\build_chain\nelson\Nelson_install.exe
- echo ici 2
- move /Y c:\build_chain\nelson\Nelson_install.exe c:\build_chain\Nelson_install.exe
- echo ici 3
- c:\build_chain\Nelson_install.exe /VERYSILENT /SUPPRESSMSGBOXES /DIR="c:\build_chain\nelson-install"
- echo ici 4
- "c:/build_chain/nelson-install/bin/x64/nelson-adv-cli --quiet -f c:/build_chain/nelson-install/tools/tests_all/runtests_all.nls"
- echo ici 5

install:
- choco install -y curl InnoSetup
- SET PATH="C:\Program Files (x86)\MSBuild\14.0\Bin\";"C:\Program Files (x86)\Inno Setup 5";%PATH%%
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

build_script:
- cd "c:\build_chain\nelson"
- msbuild nelson.sln /p:Configuration=Release /p:Platform=x64 /target:"NelSon-gui"

artifacts:
  - path: c:/build_chain/nelson/*.exe
  - path: c:/build_chain/nelson-install/tests_all.xml

notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\Nelson
