version: 0.2.1.{build}
image: Visual Studio 2017

environment:
  VS_VERSION: vs2017
  QTDIR64: C:\Qt\5.10.0\msvc2017_64
  QTDIR32: C:\Qt\5.10.0\msvc2015
  BUILD_CHAIN_DIR: c:\build_chain\nelson

branches:
  only:
    - master

platform:
- x86
- x64

matrix:
  allow_failures:
    - platform: x86

install:
- choco install -y curl InnoSetup
- ps: (new-object net.webclient).DownloadFile("https://download.microsoft.com/download/9/E/D/9ED82A62-4235-4003-A59A-9F6246073F2E/MSMpiSetup.exe", "C:\build_chain\MSMpiSetup.exe")
- C:\build_chain\MSMpiSetup.exe -unattend -minimal
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%
- SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\;C:\Program Files (x86)\Inno Setup 5;%PATH%
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%

before_build:
- C:\Python36\python c:/build_chain/nelson/tools/update_version/update_version.py
- if %platform%==x64 (set QTDIR=%QTDIR64%) else (set QTDIR=%QTDIR32%)
- if %platform%==x64 (set NELSON_PLATFORM=x64) else (set NELSON_PLATFORM=win32)
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-%NELSON_PLATFORM%.git c:\build_chain\nelson-thirdparty-%NELSON_PLATFORM%
- cd "c:\build_chain\nelson-thirdparty-%NELSON_PLATFORM%"
- install.bat

build_script:
- cd "c:\build_chain\nelson"
- msbuild nelson.sln /p:Configuration=Release /p:Platform=%NELSON_PLATFORM% /target:"NelSon-gui"  /m:4 

after_build:
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --quiet -f c:\build_chain/nelson/tools/buildhelp/buildhelp.nls
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --quiet -f c:\build_chain/nelson/tools/tests_minimal/runtests_minimal.nls
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-cli --quiet -e run('c:\build_chain/nelson/tools/innosetup/innosetup.nls');exit
- iscc c:\build_chain/nelson/tools/innosetup/Nelson.iss
- c:\build_chain/nelson/bin/%NELSON_PLATFORM%/nelson-adv-cli --quiet -f c:\build_chain/nelson/tools/tests_all/runtests_all.nls


artifacts:
  - path: ./*.exe
  - path: ./tests_all.xml

notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\Nelson
