version: 0.1.7.{build}
image: Visual Studio 2015

environment:
  VS_VERSION: vs2015
  QTDIR64: C:\Qt\5.9\msvc2015_64
  QTDIR32: C:\Qt\5.9\msvc2015
  BUILD_CHAIN_DIR: c:\build_chain\nelson

branches:
  only:
    - master

platform:
- x64
- win32

before_build:
- if not %platform%==win32 (set QTDIR=%QTDIR64%) else (set QTDIR=%QTDIR32%)
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-%platform%.git c:\build_chain\nelson-thirdparty-%platform%
- cd "c:\build_chain\nelson-thirdparty-%platform%"
- install.bat

after_build:
- c:\build_chain/nelson/bin/%platform%/nelson-cli --quiet -f c:\build_chain/nelson/tools/buildhelp/buildhelp.nls
- c:\build_chain/nelson/bin/%platform%/nelson-cli --quiet -f c:\build_chain/nelson/tools/tests_minimal/runtests_minimal.nls
- c:\build_chain/nelson/bin/%platform%/nelson-cli --quiet -e run('c:\build_chain/nelson/tools/innosetup/innosetup.nls');exit
- iscc c:\build_chain/nelson/tools/innosetup/Nelson.iss
- c:\build_chain/nelson/bin/%platform%/nelson-adv-cli --quiet -f c:\build_chain/nelson/tools/tests_all/runtests_all.nls

install:
- choco install -y curl InnoSetup
- SET PATH="C:\Program Files (x86)\MSBuild\14.0\Bin\";"C:\Program Files (x86)\Inno Setup 5";%PATH%%
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %platform%

build_script:
- cd "c:\build_chain\nelson"
- msbuild nelson.sln /p:Configuration=Release /p:Platform=%platform% /target:"NelSon-gui"

artifacts:
  - path: ./*.exe
  - path: ./tests_all.xml

notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\Nelson
