version: 0.1.2.{build}
image: Visual Studio 2015

environment:
  VS_VERSION: vs2015
  QTDIR64: C:\Qt\5.7\msvc2015_64
  QTDIR = C:\Qt\5.7\msvc2015_64

branches:
  only:
    - master

platform:
- x64
  
before_build:
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-x64.git c:\build_chain\nelson-thirdparty-x64
- cd "c:\build_chain\nelson-thirdparty-x64"
- install.bat

install:
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\Nelson
