version: 0.1.6.{build}
image: Visual Studio 2015

environment:
  VS_VERSION: vs2015
  QTDIR64: C:\Qt\5.9\msvc2015_64
  QTDIR: C:\Qt\5.9\msvc2015_64
  BUILD_CHAIN_DIR: c:\build_chain\nelson
  TESTS_RESULT_DIR: c:\build_chain\nelson
  NLS_VERSION: 0.1.6.0
branches:
  only:
    - master

platform:
- x64

before_build:
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-x64.git c:\build_chain\nelson-thirdparty-x64
- cd "c:\build_chain\nelson-thirdparty-x64"
- install.bat

after_build:
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -f c:\build_chain/nelson/tools/buildhelp/buildhelp.nls
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -f c:\build_chain/nelson/tools/tests_minimal/runtests_minimal.nls
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -e run('c:\build_chain/nelson/tools/innosetup/innosetup.nls');exit
- iscc c:\build_chain/nelson/tools/innosetup/Nelson.iss
- c:/build_chain/nelson/Nelson-%NLS_VERSION%-x86-64.exe /VERYSILENT /SUPPRESSMSGBOXES
- "c:/Program Files/Nelson-%NLS_VERSION% (64 bits)/bin/x64/nelson-adv-cli --quiet -f c:/Program Files/Nelson-%APPVEYOR_BUILD_VERSION%.0 (64 bits)/tools/tests_all/runtests_all.nls"

install:
- choco install -y curl InnoSetup
- SET PATH="C:\Program Files (x86)\MSBuild\14.0\Bin\";"C:\Program Files (x86)\Inno Setup 5";%PATH%%
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

build_script:
- cd "c:\build_chain\nelson"
- msbuild nelson.sln /p:Configuration=Release /p:Platform=x64 /target:"NelSon-gui"

artifacts:
  - path: ./*.exe
  - path: ./tests_all.xml

notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\Nelson
