version: 0.1.8.{build}
image: Visual Studio 2017

environment:
  VS_VERSION: vs2017
  QTDIR64: C:\Qt\5.9.1\msvc2017_64
  QTDIR32: C:\Qt\5.9.1\msvc2015
  BUILD_CHAIN_DIR: c:\build_chain\nelson

branches:
  only:
    - master

platform:
- x64
- win32

before_build:
- C:\Python36\python c:/build_chain/nelson/tools/update_version/update_version.py
- if %platform%==win32 (set QTDIR=%QTDIR32%) else (set QTDIR=%QTDIR64%)
- if %platform%==win32 (set PLATFORM_GIT=win32) else (set PLATFORM_GIT=x64)
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-%PLATFORM_GIT%.git c:\build_chain\nelson-thirdparty-%PLATFORM_GIT%
- cd "c:\build_chain\nelson-thirdparty-%PLATFORM_GIT%"
- git checkout vs2017
- install.bat

after_build:
- c:\build_chain/nelson/bin/%platform%/nelson-cli --quiet -f c:\build_chain/nelson/tools/buildhelp/buildhelp.nls
- c:\build_chain/nelson/bin/%platform%/nelson-cli --quiet -f c:\build_chain/nelson/tools/tests_minimal/runtests_minimal.nls
- c:\build_chain/nelson/bin/%platform%/nelson-cli --quiet -e run('c:\build_chain/nelson/tools/innosetup/innosetup.nls');exit
- iscc c:\build_chain/nelson/tools/innosetup/Nelson.iss
- c:\build_chain/nelson/bin/%PLATFORM_GIT%/nelson-adv-cli --quiet -f c:\build_chain/nelson/tools/tests_all/runtests_all.nls

install:
- choco install -y curl InnoSetup
- SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\;C:\Program Files (x86)\Inno Setup 5;%PATH%
- if %platform%==win32 (set TARGET_VS=x86) else (set TARGET_VS=x64)
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %TARGET_VS%

build_script:
- cd "c:\build_chain\nelson"
- msbuild nelson.sln /p:Configuration=Release /p:Platform=%platform% /target:"NelSon-gui"

artifacts:
  - path: ./*.exe
  - path: ./tests_all.xml

notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\Nelson
