version: 0.1.2.{build}
image: Visual Studio 2015

environment:
  VS_VERSION: vs2015
  QTDIR64: C:\Qt\5.7\msvc2015_64
  QTDIR: C:\Qt\5.7\msvc2015_64

branches:
  only:
    - master

platform:
- x64
  
before_build:
- git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-x64.git c:\build_chain\nelson-thirdparty-x64
- cd "c:\build_chain\nelson-thirdparty-x64"
- install.bat

after_build:
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -f c:\build_chain/nelson/tools/buildhelp/buildhelp.nls
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -f c:\build_chain/nelson/tools/tests_minimal/runtests_minimal.nls
- c:\build_chain/nelson/bin/x64/nelson-cli --quiet -f c:\build_chain/nelson/tools/innosetup/innosetup.nls


install:
- choco install -y InnoSetup
- SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%%
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64

build_script:
- msbuild nelson.sln /p:Configuration=Release /p:Platform=x64 /target:"NelSon-gui"

notifications:
- provider: Email
  to:
  - nelson.numerical.computation@gmail.com

# clone directory
clone_folder: c:\build_chain\Nelson
